# These are supported funding model platforms

github: Piwielle
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: Piwi_
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["https://commerce.coinbase.com/checkout/c454f288-6f7f-418a-8580-9171e25158c9"]
